hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	--hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waybar")
	hl.exec_cmd("nwg-drawer -r")
	hl.exec_cmd("fcitx5 -d")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("sleep 1; synology-drive")
end)

