# 기본 영문 폰트 설정 (원하시는 영문 고정폭 폰트 입력)
font_family Bitstream Vera Sans Mono

# 한글 유니코드 영역(자음/모음, 호환 자모, 한글 음절)을 고정폭 한글 폰트로 강제 매핑
symbol_map U+1100-U+11FF,U+3130-U+318F,U+AC00-U+D7A3 Noto Sans Mono CJK KR

#background_opacity 0.7
dynamic_background_opacity no


# BEGIN_KITTY_THEME
# Ciapre
include current-theme.conf
# END_KITTY_THEME